#!/bin/bash

TAG="$1"

USAGE="create-source-package"
SUBDIRECTORY_OK=1
. "$(git --exec-path)/git-sh-setup"

cd_to_toplevel
git archive --format=tar --prefix=${TAG}/ ${TAG} | \
    gzip > ${TAG}.tar.gz
