#!/bin/bash
# save-csp-test [test name]

# Assumes that the test programs in tests/csp generate the correct
# output for [test name], and saves this test output.  The script
# should be run from your CMake build directory, which is assumed to
# be a subdirectory of the project source tree.

if [ x$1 == x ]; then
    echo "Usage: save-csp-test [test name]"
    exit 1
fi

TEST=$1

tests/csp/test-csp0 < ../tests/csp/$TEST.csp0 > ../tests/csp/$TEST.output
tests/csp/test-prenormalize T < ../tests/csp/$TEST.csp0 > ../tests/csp/$TEST.t-prenormal-output
tests/csp/test-normalize T < ../tests/csp/$TEST.csp0 > ../tests/csp/$TEST.t-normal-output
tests/csp/test-prenormalize F < ../tests/csp/$TEST.csp0 > ../tests/csp/$TEST.f-prenormal-output
tests/csp/test-normalize F < ../tests/csp/$TEST.csp0 > ../tests/csp/$TEST.f-normal-output
